# Generated by Django 3.2.8 on 2021-10-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('usuario_nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('usuario_telefono', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('usuario_tipo_id', models.CharField(max_length=20, verbose_name='Tipo_id')),
                ('usuario_numero_id', models.IntegerField(unique=True, verbose_name='Numero_id')),
                ('usuario_ciudad', models.CharField(max_length=10, verbose_name='Ciudad')),
                ('usuario_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('usuario_email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_serial', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_categoria', models.CharField(default='null', max_length=40, verbose_name='Categoria')),
                ('prod_referencia', models.CharField(default='null', max_length=45, verbose_name='Referencia')),
                ('prod_precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('prod_descripcion', models.TextField(default='null', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('pqr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pqr_tipo_solicitud', models.CharField(help_text='Seleccione tipo de solicitud', max_length=45, verbose_name='Tipo de Solicitud')),
                ('pqr_clasificacion', models.CharField(help_text='Seleccione clasificación de solicitud', max_length=45, verbose_name='Clasificación')),
                ('pqr_descripcion', models.TextField(help_text='Describa su solicitud', max_length=80, verbose_name='Descripción')),
                ('pqr_estado', models.CharField(max_length=45, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_numero', models.AutoField(primary_key=True, serialize=False)),
                ('factura_fecha', models.DateTimeField(verbose_name='Fecha de compra')),
                ('direccion_envio', models.CharField(default='null', max_length=80, verbose_name='Direccion de envío')),
                ('metodo_pago', models.CharField(default='null', max_length=20, verbose_name='Método de pago')),
                ('valor_envio', models.IntegerField(default='null', verbose_name='valor de envío')),
                ('valor_producto', models.IntegerField(default='null', verbose_name='valor de producto')),
                ('valor_impuesto', models.IntegerField(default='null', verbose_name='valor de impuesto')),
                ('subtotal', models.IntegerField(default='null', verbose_name='Subtotal')),
                ('valor_total', models.IntegerField(default='null', verbose_name='valor total')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='authApp.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
