# Generated by Django 3.2.7 on 2021-10-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='prod_serial',
            new_name='id',
        ),
    ]
