# Generated by Django 3.2.7 on 2021-10-19 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_rename_prod_serial_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='factura_numero',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='factura',
            name='factura_fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoFactura', to='authApp.producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFactura', to=settings.AUTH_USER_MODEL),
        ),
    ]
