# Generated by Django 3.2.7 on 2021-10-19 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_auto_20211019_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqr',
            old_name='pqr_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='pqr_clasificacion',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='pqr_descripcion',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='pqr_estado',
        ),
        migrations.RemoveField(
            model_name='pqr',
            name='pqr_tipo_solicitud',
        ),
        migrations.AddField(
            model_name='pqr',
            name='clasificacion',
            field=models.CharField(default='null', max_length=45),
        ),
        migrations.AddField(
            model_name='pqr',
            name='descripcion',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='estado',
            field=models.CharField(default='null', max_length=45),
        ),
        migrations.AddField(
            model_name='pqr',
            name='tipo',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPqr', to=settings.AUTH_USER_MODEL),
        ),
    ]
